module.exports = {
    'WDAF-DT': 'FOX',
    KCTV: 'CBS',
    'KMBC-HD': 'ABC',
    'KCPT-1': 'PBS 1',
    'KCPT-2': 'PBS 2',
    'KCWE-HD': 'CW',
    'KMCI-TV': 'KMCI',
    'KSHB-TV': 'NBC',
    ION: 'ION',
    Quest: 'Quest',
    'Me TV': 'Me TV',
    'KCPT-3': 'Create',
    'KCPT-4': 'PBS Kids',
    'KMCI-B': 'Bounce',
    'KSHB-GT': 'GRIT',
    'KSHB-LF': 'LAFF',
    qubo: 'QUBO',
    IONPlus: 'ION Plus',
    LIGHTtv: 'LIGHT',
    Dabl: 'DABL',
    'Cozi TV': 'COZI',
    'KSMO-TV': 'MyNetworkTV',
}
